basic structure
front-end-by-rimantas/40-grupe-portfolio-personal pull request #35
Opened 2022-10-31 13:10 UTC by Dirigentas

2022-10-31 13:14 UTC, bozenakr requested changes

2022-10-31 13:14 UTC, bozenakr commented on index.html
> +    <main>
Ar tikrai tik tokia struktura?

2022-10-31 13:14 UTC, Dirigentas commented on index.html
> +    <main>
Taip, tik tokia

2022-10-31 13:16 UTC, bozenakr approved these changes

2022-10-31 13:17 UTC, bozenakr requested changes
Ar tikrai

2022-10-31 13:32 UTC, bozenakr submitted a review, later dismissed

2022-10-31 13:38 UTC, bozenakr commented on README.md
> +# Coming Soon
Reikia pakeist pavadinima

2022-10-31 13:39 UTC, bozenakr commented on README.md
> +Design: [Coming Soon](https://preview.colorlib.com/theme/personal/)
reikia pakeist ir cia

2022-10-31 13:43 UTC, bozenakr submitted a review, later dismissed

2022-10-31 15:21 UTC, bozenakr approved these changes

2022-11-01 07:11 UTC, Kplukas reviewed
kiek matau viskas okay atrodo

2022-11-01 07:12 UTC, Kplukas approved these changes

2022-11-01 07:12 UTC, merged