Header static html & style
front-end-by-rimantas/40-grupe-portfolio-personal pull request #74
Opened 2022-11-07 15:06 UTC by bozenakr

2022-11-07 15:11 UTC, Dirigentas requested changes
need responsive design

2022-11-07 15:14 UTC, Kplukas approved these changes

2022-11-08 11:46 UTC, Dirigentas approved these changes
LGTM

2022-11-08 12:09 UTC, Paulius7778hhh approved these changes

2022-11-08 12:10 UTC, merged